### ISSUE TITLE
Add a list of streamers that use it.

### ISSUE THREAD

**Issue by manreo** [Fittiboy/bitcoin-on-twitch#11]
I'll be happy to browse all streamers that use this extension..

**Comment by Fittiboy** [comment]
That would be pretty cool to have!
But currently that's probably only me, and tracking who actually uses it would likely be a nightmare :/

**Comment by Fittiboy** [comment]
That being said, I _could_ add a list in the README.md for people to pull request themselves and other streamers into. That way we have at least _something_!
