### ISSUE TITLE
Create LNbits extension

### ISSUE THREAD

**Issue by Fittiboy** [Fittiboy/bitcoin-on-twitch#7]
Optimally, parts of this repo should become an [LNbits](https://github.com/lnbits/lnbits) extension:  
* Most of what is currently in `settings.json` could be set via UI
* API endpoint that serves as redirect for Streamlabs `access_token` (essentially `wait_for_token.py`)
* `webhook.py` as background service

The extension should also allow modification of the donation format that is sent [here](https://github.com/Fittiboy/bitcoin-on-twitch/blob/6096177f25506136ee93c85e0e74a288521337a0/webhook.py#L49).  

The extension's front end would ideally be a simple tipping form that asks for "Name," "Message," and "Amount" in either sats or any of the [supported currencies](https://streamlabs.readme.io/docs/currency-codes), converting the amount to sats to create an invoice.  
Another option that would be great to have available is a Twitch login button that auto-fills the "Name" field, and sets the `identifier` to a unique ID value, like the Twitch User ID (see [here](https://dev.streamlabs.com/reference#donations-1)).  

I've created a branch to work on this: https://github.com/Fittiboy/lnbits/tree/TwitchAlerts
Will be closed by lnbits/lnbits#227

**Comment by Fittiboy** [comment]
I personally have 0 front end experience, so I would need someone else to do pretty much the entire front end work.  
Back end should be no issue for me to handle, as that is what I do in this repo either way.

**Comment by Fittiboy** [comment]
@arcbtc  
You've mentioned interest on Twitter, as you're working on your own extension for streamers (lnbits/lnbits#183).  
This one obviously has a different focus though, which is integrating Bitcoin donations with existing stream alert systems.  
Would you personally want to work on this, or do you maybe know someone who would?  
I'm also having issues even [following this guide](https://lnbits.org/devs/development.html), but I've not spent much time on that yet.

**Comment by fiatjaf** [comment]
So you're familiar with Python on the backend, right? If you start from there and expose an API like the other extensions I can make a very stupid default frontend for you, and then you can adapt that as you please.

I recommend looking at other extensions that do something instead of just the "example" extensions.

**Comment by Fittiboy** [comment]
That sounds perfect, thank you so much! :+1: 
I've taken a look at the other extensions yesterday, and from the looks of it I'll definitely be able to handle the backend myself. I'll get back to you when I've got that all figured out, so you can start working on connecting a frontend.

**Comment by Fittiboy** [comment]
Extension almost ready.
